In [3]:
import numpy as np 
array=np.array([12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30])
reverse =np.flip(array)
print(reverse)

[30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]


In [5]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) 
for x in range (0,len(a)): 
    a[x]=np.flip(a[x]) 
print(a)

[[ 3  2  1]
 [ 6  5  4]
 [ 9  8  7]
 [12 11 10]]


In [6]:
import numpy as np
x= np.arange(12,38)
print ("Original array")
print(x)
print("Reverse array")
x=x[::-1]
print(x)

Original array
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]
